html links fetcher
risboo6909/librarian pull request #2
Opened 2020-07-17 07:25 UTC by bodagovsky

2020-07-19 21:44 UTC, risboo6909 requested changes

2020-07-19 21:44 UTC, risboo6909 commented on src/parser.rs
> +pub(crate) fn fetch(url: String) -> Vec<String> {
Можешь, плиз, заюзать тут либу [surf](https://docs.rs/surf/1.0.3/surf/), для единообразия с [Crawler](https://docs.rs/surf/1.0.3/surf/) и не забудь, плиз, там таймаут тоже заюзать.

2020-07-19 21:46 UTC, risboo6909 commented on src/parser.rs
> +    let req = reqwest::blocking::get(&url).unwrap();
Еще обработку ошибок надо нормально сделать, негоже вылетать из программы, если `url` вдруг недоступен или еще что-то подобное. Лучше логировать и продолжать работать, попробовать позже.

2020-07-20 06:38 UTC, bodagovsky commented on src/parser.rs
> +pub(crate) fn fetch(url: String) -> Vec<String> {
я хотел так сделать, но не нашел там блокирующий запрос. Там только асинк?

2020-07-20 08:01 UTC, risboo6909 commented on src/parser.rs
> +pub(crate) fn fetch(url: String) -> Vec<String> {
Вроде бы да. Как раз первый шажок в асинк будет!

2020-07-22 19:28 UTC, risboo6909 approved these changes

2020-07-22 19:32 UTC, merged