document body
risboo6909/librarian pull request #4
Opened 2020-07-30 19:49 UTC by bodagovsky

2020-07-30 21:38 UTC, risboo6909 requested changes
Не забывай делать cargo clippy + cargo build перед созданием пулл-риквеста, а то этот не скомпилялся бы)))

2020-07-30 21:38 UTC, risboo6909 commented on src/main.rs
> +use chrono::Duration;
уже определено выше, не скомпилится же)

2020-07-30 21:38 UTC, risboo6909 commented on src/scheduler.rs
> +    pub(crate) fn add_indexer(&mut self, indexer: Box<dyn IndexerTrait>) -> Result<(), Error> {
Не скомпилится, `Error` нигде не определен.
Верни, плиз, объявление ф-ии, оно же работало вроде.

2020-07-30 21:38 UTC, risboo6909 commented on src/model.rs
> +    fn new() -> Self {
ф-ия должна быть `pub(crate)`, иначе ее не получится нигде использовать

2020-07-30 21:38 UTC, risboo6909 commented on src/model.rs
> +pub(crate) struct Library {
Давай как-нибудь иначе это назовем, это же не библиотека, а только запись в базе, можно назвать `Item` или может придумаешь что-то получше.

2020-07-30 21:38 UTC, risboo6909 commented on src/model.rs
> +    fn new() -> Self {
кстати, зачем она нам в таком виде? мы будем сразу создавать структуру с заполненными полями

2020-07-30 21:38 UTC, risboo6909 commented on src/model.rs
> +    fn new() -> Self {
сюда хорошо бы прикрутить builder pattern, см. https://doc.rust-lang.org/1.0.0/style/ownership/builders.html

2020-07-31 05:57 UTC, bodagovsky commented on src/scheduler.rs
> +    pub(crate) fn add_indexer(&mut self, indexer: Box<dyn IndexerTrait>) -> Result<(), Error> {
блин, это случайно получилось, когда делал rebase. не заметил

2020-07-31 05:58 UTC, bodagovsky commented on src/model.rs
> +pub(crate) struct Library {
да, ты прав

2020-07-31 05:58 UTC, bodagovsky commented on src/main.rs
> +use chrono::Duration;
это тоже не заметил, потом уже только исправил

2020-07-31 06:08 UTC, bodagovsky commented on src/model.rs
> +    fn new() -> Self {
хорошо

2020-07-31 07:08 UTC, risboo6909 commented on src/scheduler.rs
> +    pub(crate) fn add_indexer(&mut self, indexer: Box<dyn IndexerTrait>) -> Result<(), Error> {
Аа, Оки)

2020-07-31 08:37 UTC, risboo6909 commented on src/model.rs
> +    pub(crate) fn name(mut self, n: String) -> Self {
норм, только сделай плиз везде не `String`, а `&str` и внутри ф-ий делай `to_owned()`

2020-07-31 08:52 UTC, risboo6909 approved these changes

2020-07-31 08:56 UTC, merged