sending vec of docs to meilisearch
risboo6909/librarian pull request #5
Opened 2020-08-03 16:16 UTC by bodagovsky

2020-08-03 21:12 UTC, risboo6909 commented
Слушай, а я так и не понял, почему падали тесты? )))

2020-08-03 21:12 UTC, risboo6909 requested changes

2020-08-03 21:12 UTC, risboo6909 commented on src/main.rs
> +mod save;
Давай единственное что - назовем иначе, там же не токмо `save` будет.
Еще там должна быть ф-ия для получения списка всех документов из `meilisearch` по какому-либо полю.

2020-08-03 21:12 UTC, risboo6909 commented on src/save.rs
> +pub(crate) async fn send(url: &str, docs: &Vec<Document>) -> Result<String, Err> {
Тут конечно круто было бы структуру сделать, типа sender'а или как-то объявить `url` статикой, чтобы его не надо было каждый раз передавать в ф-ии. Он же не будет меняться в принципе.

2020-08-03 21:14 UTC, bodagovsky commented on src/save.rs
> +pub(crate) async fn send(url: &str, docs: &Vec<Document>) -> Result<String, Err> {
Да, я думал об этом. Сделаю структурой пока, а потом будем хранить в ямлах. Предлагаю так

2020-08-03 21:25 UTC, risboo6909 commented on src/save.rs
> +pub(crate) async fn send(url: &str, docs: &Vec<Document>) -> Result<String, Err> {
Нене, я про то, что вот эту штуку, которая взаимодействует с апи `meilisearch` сделать в виде объекта. См. Как `Crawler` сделан

2020-08-03 21:30 UTC, bodagovsky commented
http:// надо было добавить

2020-08-03 21:32 UTC, bodagovsky commented on src/save.rs
> +pub(crate) async fn send(url: &str, docs: &Vec<Document>) -> Result<String, Err> {
Ну да, я так и подумал. Просто я подумал, что можно было бы объявлять пока переменную глобально, чтобы она хранила адрес в поле

2020-08-03 21:34 UTC, risboo6909 commented on src/save.rs
> +pub(crate) async fn send(url: &str, docs: &Vec<Document>) -> Result<String, Err> {
Ок. Меня просто ямлы смутили))

2020-08-04 06:38 UTC, bodagovsky commented
> Слушай, а я так и не понял, почему падали тесты? )))

потому что надо было добавить http:// к адресам

2020-08-04 18:21 UTC, risboo6909 commented on src/accountant.rs
> +pub(crate) const URL: &'static str = "http://meilisearch.api";
Еще круче потом будет это в конфиги вынести, но не сейчас, пока пусть так.

2020-08-04 18:21 UTC, risboo6909 approved these changes

2020-08-04 18:51 UTC, merged